export enum Main {
	UpdateTheme = 'update-theme',
	GetTheme = 'get-theme',
	GetLocale = 'get-locale',
	GetAccentColor = 'get-accent-color',
	MqttConnect = 'connect',
	MqttDisconnect = 'disconnect',
	MqttSubscribe = 'subscribe',
	MqttUnsubscribe = 'unsubscribe',
	MqttPublish = 'publish',
	MqttOnConnect = 'on-connect',
	MqttOnDisconnect = 'on-disconnect',
	MqttOnError = 'on-error',
	MqttConnected = 'connected',
	MqttConnectedBatch = 'connected-batch',
	OpenFileDialog = 'open-file-dialog',
}
