export enum Main {
	UpdateTheme = 'update-theme',
	GetTheme = 'get-theme',
	GetLocale = 'get-locale',
	GetAccentColor = 'get-accent-color',
	OnAccentColorChanged = 'on-accent-color-changed',
	MqttConnect = 'connect',
	MqttDisconnect = 'disconnect',
	MqttSubscribe = 'subscribe',
	MqttUnsubscribe = 'unsubscribe',
	MqttPublish = 'publish',
	OnMqttConnect = 'on-connect',
	OnMqttDisconnect = 'on-disconnect',
	OnMqttError = 'on-error',
	OnMqttMessage = 'on-message',
	MqttConnected = 'connected',
	MqttConnectedBatch = 'connected-batch',
	OpenFileDialog = 'open-file-dialog',
}
